In [39]:
from operator import index

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
df = pd.read_csv('../data/Telco-Customer-Churn-Cleaned.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_year
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0-1 Year
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,2-3 Years
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0-1 Year
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,3-4 Years
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0-1 Year

In [41]:
df['is_high_risk_billing'] = np.where((df['PaymentMethod'] == "Electronic check") & (df['Contract'] == "Month-to-month"), 1, 0)
df['is_high_risk_billing'].head()
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_year,is_high_risk_billing
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0-1 Year,1
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.50,No,2-3 Years,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0-1 Year,0
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,3-4 Years,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0-1 Year,1

In [42]:
services = ['PhoneService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']

df['Total_Services'] = (df[services] == 'Yes').sum(axis=1)

In [43]:
columns = df.select_dtypes(include=['object', 'str']).columns
print(columns)
for c in columns:
    print(c)
    print(df[c].unique())
    print("-----------------------------------")

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn',
       'tenure_year'],
      dtype='str')
customerID
<StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7032, dtype: str
-----------------------------------
gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
-----------------------------------
Partner
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
-----------------------------------
Dependents
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------------------------
PhoneService
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------------------------
MultipleLines
<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
-----------------------------------
InternetService
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
-----------------------------------
OnlineSecurity
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------------------------
OnlineBackup
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
-----------------------------------
DeviceProtection
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------------------------
TechSupport
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------------------------
StreamingTV
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------------------------
StreamingMovies
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------------------------
Contract
<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
-----------------------------------
PaperlessBilling
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
-----------------------------------
PaymentMethod
<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
-----------------------------------
Churn
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------------------------
tenure_year
<StringArray>
['0-1 Year', '2-3 Years', '3-4 Years', '1-2 Years', '5+ Years', '4-5 Years']
Length: 6, dtype: str
-----------------------------------

In [44]:
binary_columns= ['gender', 'Partner', 'Dependents', 'PhoneService', 'OnlineSecurity', 'OnlineBackup','DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling']

nominal_columns= ['MultipleLines', 'InternetService', 'Contract', 'PaymentMethod', 'tenure_year' ]

In [45]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

encoder = OneHotEncoder(drop= 'first', sparse_output=False)

encoded_data = encoder.fit_transform(df[binary_columns])

encoded_df = pd.DataFrame(
    encoded_data,
    columns=encoder.get_feature_names_out(binary_columns),
    index= df.index,
)

final_df = pd.concat(
    [df.drop(columns=binary_columns), encoded_df],
    axis=1
)

print("\nOne-Hot Encoded Data:")
print(final_df)

final_df.head()

One-Hot Encoded Data:
      customerID  SeniorCitizen  tenure     MultipleLines InternetService  \
0     7590-VHVEG              0       1  No phone service             DSL
1     5575-GNVDE              0      34                No             DSL
2     3668-QPYBK              0       2                No             DSL
3     7795-CFOCW              0      45  No phone service             DSL
4     9237-HQITU              0       2                No     Fiber optic
...          ...            ...     ...               ...             ...
7027  6840-RESVB              0      24               Yes             DSL
7028  2234-XADUH              0      72               Yes     Fiber optic
7029  4801-JZAZL              0      11  No phone service             DSL
7030  8361-LTMKD              1       4               Yes     Fiber optic
7031  3186-AJIEK              0      66                No     Fiber optic

            Contract              PaymentMethod  MonthlyCharges  TotalCharges  \
0     Month-to-month           Electronic check           29.85         29.85
1           One year               Mailed check           56.95       1889.50
2     Month-to-month               Mailed check           53.85        108.15
3           One year  Bank transfer (automatic)           42.30       1840.75
4     Month-to-month           Electronic check           70.70        151.65
...              ...                        ...             ...           ...
7027        One year               Mailed check           84.80       1990.50
7028        One year    Credit card (automatic)          103.20       7362.90
7029  Month-to-month           Electronic check           29.60        346.45
7030  Month-to-month               Mailed check           74.40        306.60
7031        Two year  Bank transfer (automatic)          105.65       6844.50

     Churn  ... Partner_Yes  Dependents_Yes  PhoneService_Yes  \
0       No  ...         1.0             0.0               0.0
1       No  ...         0.0             0.0               1.0
2      Yes  ...         0.0             0.0               1.0
3       No  ...         0.0             0.0               0.0
4      Yes  ...         0.0             0.0               1.0
...    ...  ...         ...             ...               ...
7027    No  ...         1.0             1.0               1.0
7028    No  ...         1.0             1.0               1.0
7029    No  ...         1.0             1.0               0.0
7030   Yes  ...         1.0             0.0               1.0
7031    No  ...         0.0             0.0               1.0

      OnlineSecurity_Yes  OnlineBackup_Yes  DeviceProtection_Yes  \
0                    0.0               1.0                   0.0
1                    1.0               0.0                   1.0
2                    1.0               1.0                   0.0
3                    1.0               0.0                   1.0
4                    0.0               0.0                   0.0
...                  ...               ...                   ...
7027                 1.0               0.0                   1.0
7028                 0.0               1.0                   1.0
7029                 1.0               0.0                   0.0
7030                 0.0               0.0                   0.0
7031                 1.0               0.0                   1.0

      TechSupport_Yes  StreamingTV_Yes  StreamingMovies_Yes  \
0                 0.0              0.0                  0.0
1                 0.0              0.0                  0.0
2                 0.0              0.0                  0.0
3                 1.0              0.0                  0.0
4                 0.0              0.0                  0.0
...               ...              ...                  ...
7027              1.0              1.0                  1.0
7028              0.0              1.0                  1.0
7029              0.0              0.0                  0.0
7030              0.0              0.0                  0.0
7031              1.0              1.0                  1.0

      PaperlessBilling_Yes
0                      1.0
1                      0.0
2                      1.0
3                      0.0
4                      1.0
...                    ...
7027                   1.0
7028                   1.0
7029                   1.0
7030                   1.0
7031                   1.0

[7032 rows x 24 columns]

,customerID,SeniorCitizen,tenure,MultipleLines,InternetService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn,...,Partner_Yes,Dependents_Yes,PhoneService_Yes,OnlineSecurity_Yes,OnlineBackup_Yes,DeviceProtection_Yes,TechSupport_Yes,StreamingTV_Yes,StreamingMovies_Yes,PaperlessBilling_Yes
0,7590-VHVEG,0,1,No phone service,DSL,Month-to-month,Electronic check,29.85,29.85,No,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,5575-GNVDE,0,34,No,DSL,One year,Mailed check,56.95,1889.50,No,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,3668-QPYBK,0,2,No,DSL,Month-to-month,Mailed check,53.85,108.15,Yes,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
3,7795-CFOCW,0,45,No phone service,DSL,One year,Bank transfer (automatic),42.30,1840.75,No,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
4,9237-HQITU,0,2,No,Fiber optic,Month-to-month,Electronic check,70.70,151.65,Yes,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [46]:
final_df['Churn'] = np.where(df['Churn'] == "Yes", 1, 0)
final_df.head()

,customerID,SeniorCitizen,tenure,MultipleLines,InternetService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn,...,Partner_Yes,Dependents_Yes,PhoneService_Yes,OnlineSecurity_Yes,OnlineBackup_Yes,DeviceProtection_Yes,TechSupport_Yes,StreamingTV_Yes,StreamingMovies_Yes,PaperlessBilling_Yes
0,7590-VHVEG,0,1,No phone service,DSL,Month-to-month,Electronic check,29.85,29.85,0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,5575-GNVDE,0,34,No,DSL,One year,Mailed check,56.95,1889.50,0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,3668-QPYBK,0,2,No,DSL,Month-to-month,Mailed check,53.85,108.15,1,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
3,7795-CFOCW,0,45,No phone service,DSL,One year,Bank transfer (automatic),42.30,1840.75,0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
4,9237-HQITU,0,2,No,Fiber optic,Month-to-month,Electronic check,70.70,151.65,1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [47]:
encoder2 = OrdinalEncoder()

encoded_data = encoder2.fit_transform(final_df[nominal_columns])

encoded_df = pd.DataFrame(
    encoded_data,
    columns=encoder2.get_feature_names_out(nominal_columns),
)

df = pd.concat(
    [final_df.drop(columns=nominal_columns), encoded_df],
    axis=1
)

print("\nOrdinal Encoded Data:")
print(df)

Ordinal Encoded Data:
      customerID  SeniorCitizen  tenure  MonthlyCharges  TotalCharges  Churn  \
0     7590-VHVEG              0       1           29.85         29.85      0
1     5575-GNVDE              0      34           56.95       1889.50      0
2     3668-QPYBK              0       2           53.85        108.15      1
3     7795-CFOCW              0      45           42.30       1840.75      0
4     9237-HQITU              0       2           70.70        151.65      1
...          ...            ...     ...             ...           ...    ...
7027  6840-RESVB              0      24           84.80       1990.50      0
7028  2234-XADUH              0      72          103.20       7362.90      0
7029  4801-JZAZL              0      11           29.60        346.45      0
7030  8361-LTMKD              1       4           74.40        306.60      1
7031  3186-AJIEK              0      66          105.65       6844.50      0

      is_high_risk_billing  Total_Services  gender_Male  Partner_Yes  ...  \
0                        1               1          0.0          1.0  ...
1                        0               3          1.0          0.0  ...
2                        0               3          1.0          0.0  ...
3                        0               3          1.0          0.0  ...
4                        1               1          0.0          0.0  ...
...                    ...             ...          ...          ...  ...
7027                     0               6          1.0          1.0  ...
7028                     0               5          0.0          1.0  ...
7029                     1               1          0.0          1.0  ...
7030                     0               1          1.0          1.0  ...
7031                     0               6          1.0          0.0  ...

      DeviceProtection_Yes  TechSupport_Yes  StreamingTV_Yes  \
0                      0.0              0.0              0.0
1                      1.0              0.0              0.0
2                      0.0              0.0              0.0
3                      1.0              1.0              0.0
4                      0.0              0.0              0.0
...                    ...              ...              ...
7027                   1.0              1.0              1.0
7028                   1.0              0.0              1.0
7029                   0.0              0.0              0.0
7030                   0.0              0.0              0.0
7031                   1.0              1.0              1.0

      StreamingMovies_Yes  PaperlessBilling_Yes  MultipleLines  \
0                     0.0                   1.0            1.0
1                     0.0                   0.0            0.0
2                     0.0                   1.0            0.0
3                     0.0                   0.0            1.0
4                     0.0                   1.0            0.0
...                   ...                   ...            ...
7027                  1.0                   1.0            2.0
7028                  1.0                   1.0            2.0
7029                  0.0                   1.0            1.0
7030                  0.0                   1.0            2.0
7031                  1.0                   1.0            0.0

      InternetService  Contract  PaymentMethod  tenure_year
0                 0.0       0.0            2.0          0.0
1                 0.0       1.0            3.0          2.0
2                 0.0       0.0            3.0          0.0
3                 0.0       1.0            0.0          3.0
4                 1.0       0.0            2.0          0.0
...               ...       ...            ...          ...
7027              0.0       1.0            3.0          1.0
7028              1.0       1.0            1.0          5.0
7029              0.0       0.0            2.0          0.0
7030              1.0       0.0            3.0          0.0
7031              1.0       2.0            0.0          5.0

[7032 rows x 24 columns]

In [48]:
df.head()

,customerID,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,is_high_risk_billing,Total_Services,gender_Male,Partner_Yes,...,DeviceProtection_Yes,TechSupport_Yes,StreamingTV_Yes,StreamingMovies_Yes,PaperlessBilling_Yes,MultipleLines,InternetService,Contract,PaymentMethod,tenure_year
0,7590-VHVEG,0,1,29.85,29.85,0,1,1,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0
1,5575-GNVDE,0,34,56.95,1889.50,0,0,3,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,2.0
2,3668-QPYBK,0,2,53.85,108.15,1,0,3,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0,0.0
3,7795-CFOCW,0,45,42.30,1840.75,0,0,3,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0
4,9237-HQITU,0,2,70.70,151.65,1,1,1,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0

In [49]:
df.drop('customerID', axis=1, inplace=True)
df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,is_high_risk_billing,Total_Services,gender_Male,Partner_Yes,Dependents_Yes,...,DeviceProtection_Yes,TechSupport_Yes,StreamingTV_Yes,StreamingMovies_Yes,PaperlessBilling_Yes,MultipleLines,InternetService,Contract,PaymentMethod,tenure_year
0,0,1,29.85,29.85,0,1,1,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0
1,0,34,56.95,1889.50,0,0,3,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,2.0
2,0,2,53.85,108.15,1,0,3,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0,0.0
3,0,45,42.30,1840.75,0,0,3,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0
4,0,2,70.70,151.65,1,1,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   SeniorCitizen         7032 non-null   int64
 1   tenure                7032 non-null   int64
 2   MonthlyCharges        7032 non-null   float64
 3   TotalCharges          7032 non-null   float64
 4   Churn                 7032 non-null   int64
 5   is_high_risk_billing  7032 non-null   int64
 6   Total_Services        7032 non-null   int64
 7   gender_Male           7032 non-null   float64
 8   Partner_Yes           7032 non-null   float64
 9   Dependents_Yes        7032 non-null   float64
 10  PhoneService_Yes      7032 non-null   float64
 11  OnlineSecurity_Yes    7032 non-null   float64
 12  OnlineBackup_Yes      7032 non-null   float64
 13  DeviceProtection_Yes  7032 non-null   float64
 14  TechSupport_Yes       7032 non-null   float64
 15  StreamingTV_Yes       7032 non-null   float64
 16  StreamingMovies_Yes   7032 non-null   float64
 17  PaperlessBilling_Yes  7032 non-null   float64
 18  MultipleLines         7032 non-null   float64
 19  InternetService       7032 non-null   float64
 20  Contract              7032 non-null   float64
 21  PaymentMethod         7032 non-null   float64
 22  tenure_year           7032 non-null   float64
dtypes: float64(18), int64(5)
memory usage: 1.2 MB

In [51]:
df.to_csv('../data/Telco-Customer-Churn-Engineered.csv', index=False)
print("Başarıyla kaydedildi.")

Başarıyla kaydedildi.

In [52]:
import joblib
joblib.dump(encoder, '../models/telco_churn_encoder.pkl')

['../models/telco_churn_encoder.pkl']

In [53]:
joblib.dump(encoder2, '../models/telco_churn_encoder2.pkl')

['../models/telco_churn_encoder2.pkl']